config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  resources :users, only: [:show]
  resources :carts
  resources :orders
  resources :items
  resources :join_table_item_carts, only: [:create, :destroy]
  root to: "items#index"

  namespace :admin do
    root to: "index#index"
    resources :users
    resources :items
    resources :orders, only: [:index, :destroy]
  end

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :join_table_item_carts, dependent: :destroy
  has_many :items, through: :join_table_item_carts
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image_url, presence: true
  has_many :join_table_item_carts
  has_many :carts, through: :join_table_item_carts
  has_many :join_table_item_orders
  has_many :orders, through: :join_table_item_orders

end

app/models/join_table_item_cart.rb
class JoinTableItemCart < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

app/models/join_table_item_order.rb
class JoinTableItemOrder < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord

  after_create :new_order_mail


  # validates :item_name, presence: true
  # validates :price, presence: true
  # validates :quantity, presence: true
  # validates :payment_method, presence: true
  belongs_to :user
  has_many :join_table_item_orders, dependent: :destroy
  has_many :items, through: :join_table_item_orders

  private

  def new_order_mail
    OrderMailer.new_order_mail_to_client(self).deliver_now
    OrderMailer.new_order_mail_to_admin(self).deliver_now
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy

  after_create :create_cart, :welcome_new_user

  def create_cart
    Cart.create(
      user_id: User.last.id
    )
  end

  def welcome_new_user
    UserMailer.welcome_new_user(self).deliver_now
  end

end

app/controllers/admin/items_controller.rb
class Admin::ItemsController < ApplicationController
  before_action :is_admin?

  def index
    @items = Item.all
  end

  def edit
    @item = Item.find(params[:id])
  end

  def update
    @item = Item.find(params[:id])
    @item.update(post_params)

    if @item.save
      flash[:success] = "L'article a été mis à jour avec succès !"
      redirect_to admin_items_path
    else
      flash[:error] = "Une erreur est survenue lors de la mise à jour de l'article"
      redirect_to admin_items_path
    end

  end

  def destroy
    @item = Item.find(params[:id])

    if @item.destroy
      flash[:success] = "L'article a correctement été supprimé !"
      redirect_to admin_items_path
    else
      flash[:error] = "Erreur lors de la suppression de l'article"
      redirect_to admin_items_path
    end
    
  end

  private

  def post_params
    return params.require(:item).permit(:title, :description, :price)
  end
  
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
  end

  def is_admin?
    if user_signed_in? && current_user.admin == true
      return true
    else
      flash[:error] = "Vous n'êtes pas autorisé à effectuer cette action"
      redirect_to root_path
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_current_user_profile_page?, only: [:show]

  def show
    @user = current_user
    @cart = Cart.find(params[:id])
    @total_price = 0
    @cart.items.each do |item|
      @total_price += item.price 
    end
  end

  def update
    @cart_of_user = User.find(current_user.id).cart
    @cart_of_user.items << Item.find(item_params[:item_id])
    flash[:success] = flash[:success] = "Ce produit a été ajouté au panier."
    redirect_to root_path
  end

  private

  def is_current_user_profile_page?
    if current_user == User.find(params[:id])
    else
      redirect_to root_path
    end
  end
  
  def item_params
    params.permit(:item_id)
  end

  def cart_params
    params.permit(:id)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end
  
  def create
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: "Paiement de foobarlol",
      currency: 'eur',
    })
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    
  end

end

app/controllers/join_table_item_carts_controller.rb
class JoinTableItemCartsController < ApplicationController
  before_action :authenticate_user!
  
  def destroy
    @item = Cart.find(params[:cart_id]).items.find(params[:item_id]).join_table_item_carts.find_by(cart_id: params[:cart_id])
    @item.destroy
    flash[:success] = "Ce produit a été retiré du panier."
    redirect_to cart_path(params[:cart_id])
  end

  def create
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    @amount = order_params[:total_price].to_i*100 # amount in cents
    @cart = Cart.find(order_params[:cart_id])

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
      })

    @order = Order.new(
      user_id: current_user.id,
      quantity: @cart.items.count,
      price: order_params[:total_price]
    )
    if @order.save
      @order.items << @cart.items
      @cart.join_table_item_carts.destroy_all
      redirect_to root_path
    end

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to orders_path
    end

    private

    def order_params
      params.permit(:cart_id, :total_price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_current_user_profile_page?, only: [:show]

  def show
  end

  private

  def is_current_user_profile_page?
    if current_user == User.find(params[:id])
    else
      redirect_to root_path
    end
  end
  
end

app/helpers/admin/index_helper.rb
module Admin::IndexHelper
end

app/helpers/admin/items_helper.rb
module Admin::ItemsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def item_chosen
    
  end

  def bootstrap_class_for_flash(type)
    case type
      when 'notice' then "alert-info"
      when 'success' then "alert-success"
      when 'error' then "alert-danger"
      when 'alert' then "alert-warning"
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/join_table_item_carts_helper.rb
module JoinTableItemCartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/items/edit.html.erb
<div class="container mt-5">

  <h1 class="text-center mb-5">Modification d'un produit</h1>

  <%= form_for(@item, url: admin_item_path(@item.id)) do |f| %>

    <div class="field form-group">
      <%= f.label :title, "Titre :" %><br>
      <%= f.text_field :title, autofocus: true, autocomplete: "title", class: "form-control" %>
    </div>

    <div class="field form-group">
      <%= f.label :description, "Description :" %><br>
      <%= f.text_area :description, autocomplete: "description", class: "form-control" %>
    </div>
    
    <div class="field form-group">
      <%= f.label :price, "Prix :" %><br>
      <%= f.text_field :price, autocomplete: "price", class: "form-control" %>
    </div>

    <div class="actions text-right">
      <%= f.submit "Mettre à jour", class: "btn btn-primary" %>
    </div>

  <%end%>

</div>

app/views/admin/items/index.html.erb
<div class="container mt-5">
  <h1 class="text-center">Liste des articles</h1>

  <table class="table text-center mt-5">
    <thead>
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Titre</th>
        <th scope="col">Description</th>
        <th scope="col">Prix</th>
        <th scope="col">Edition</th>
        <th scope="col">Suppression</th>
      </tr>
    </thead>
    <tbody>
      <% @items.each do |item| %>
        <tr>
          <th scope="row"><%= item.id %></th>
          <td><%= item.title %></td>
          <td><%= item.description %></td>
          <td><%= item.price %>€</td>
          <td><%= link_to "Editer", edit_admin_item_path(item.id), class: "btn btn-primary" %></td>
          <td><%= link_to "Supprimer", admin_item_path(item.id), method: :delete, class: "btn btn-danger" %></td>
        </tr>
      <%end%>
    </tbody>
  </table>
</div>

app/views/items/index.html.erb
<div class="jumbotron cat-hero-index-image text-white" style="height: 700px;">
  <div class="container text-center">
    <h1 class="display-2">Catz Temple</h1>
    <h1 class="lead">Pour l'amour des chats</h1>
    <br>
    <p class="">Le premier magasin de photos de chats au monde</p>
    <p class="lead"></p>
  </div>
</div>

<div class="container">
  <div class="card-group">
    <% @items.each do |item|%>
      <div class="col-md-4 mt-2 mt-sm-0 card-container mb-3 tex">
        <div class="card text-center product p-4 pt-5 border-0 h-100 rounded-0 cat-card-index shadow">
          <a href="/items/<%=item.id%>"><img class="img-fluid d-block mx-auto" src="<%= item.image_url %>" alt="Pilot Aviator Glasses Gear Image"></a>
          <div class="card-body p-4 py-0 h-xs-440p">
            <h5 class="card-title font-weight-semi-bold mb-3 w-xl-220p mx-auto"><%= link_to item.title, item_path(item.id), style: "text-decoration: none !important;"%></h5>
            <h6><%= item.price %> €</h6>
          </div>
          <p class="btn w-100 px-4 mx-auto">
          <% if current_user.present? %>
          <%= link_to "Acheter", cart_path(current_user.id, :item_id => item.id), method: :put, class: "btn btn-dark btn-lg w-100" %>
        <% else %>
          <%= link_to "Acheter", new_user_registration_path, class: "btn btn-dark btn-lg w-100" %>
        <% end %>
          </p>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/items/show.html.erb
<div class="container mx-auto mt-5">
  <div class="row mt-5 mx-auto bg-light" style="border-radius: 10px;">
    <div class="event-haut row mt-3">


      <div class="col-1 ">
      </div>

      <div class="image-haut-event col-4 mr-5" >
        <img src="<%= @item.image_url %>" width="100%" height="90%" style="border-radius: 10px;"  alt="">
      </div>

      <div class="event-text col-6">
        <h3><%= @item.title %></h3>
        <h5 class="mt-3 mb-3"><%= @item.price %> €</h5>
        <p><%= @item.description %></p>

        <hr>
        <% if current_user.present? %>
          <%= link_to "Ajouter au panier", cart_path(current_user.id, :item_id => @item.id), method: :put, class: "btn btn-primary mx-auto ml-3" %>
        <% else %>
          <%= link_to "Ajouter au panier", new_user_registration_path, class: "btn btn-primary mx-auto ml-3" %>
        <% end %>
      </div>
    </div>
  </div>
</div>