config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  resources :users, only: [:show]
  resources :carts
  resources :orders
  resources :items
  resources :join_table_item_carts, only: [:create, :destroy]
  root to: "items#index"

  namespace :admin do
    root to: "index#index"
    resources :users
    resources :items
    resources :orders, only: [:index, :destroy]
  end

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :join_table_item_carts, dependent: :destroy
  has_many :items, through: :join_table_item_carts
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image_url, presence: true
  has_many :join_table_item_carts
  has_many :carts, through: :join_table_item_carts
  has_many :join_table_item_orders
  has_many :orders, through: :join_table_item_orders

end

app/models/join_table_item_cart.rb
class JoinTableItemCart < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

app/models/join_table_item_order.rb
class JoinTableItemOrder < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord

  after_create :new_order_mail


  # validates :item_name, presence: true
  # validates :price, presence: true
  # validates :quantity, presence: true
  # validates :payment_method, presence: true
  belongs_to :user
  has_many :join_table_item_orders, dependent: :destroy
  has_many :items, through: :join_table_item_orders

  private

  def new_order_mail
    OrderMailer.new_order_mail_to_client(self).deliver_now
    OrderMailer.new_order_mail_to_admin(self).deliver_now
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy

  after_create :create_cart, :welcome_new_user

  def create_cart
    Cart.create(
      user_id: User.last.id
    )
  end

  def welcome_new_user
    UserMailer.welcome_new_user(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
  end

  def is_admin?
    if user_signed_in? && current_user.admin == true
      return true
    else
      flash[:error] = "Vous n'êtes pas autorisé à effectuer cette action"
      redirect_to root_path
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_current_user_profile_page?, only: [:show]

  def show
    @user = current_user
    @cart = Cart.find(params[:id])
    @total_price = 0
    @cart.items.each do |item|
      @total_price += item.price 
    end
  end

  def update
    @cart_of_user = User.find(current_user.id).cart
    @cart_of_user.items << Item.find(item_params[:item_id])
    flash[:success] = flash[:success] = "Ce produit a été ajouté au panier."
    redirect_to root_path
  end

  private

  def is_current_user_profile_page?
    if current_user == User.find(params[:id])
    else
      redirect_to root_path
    end
  end
  
  def item_params
    params.permit(:item_id)
  end

  def cart_params
    params.permit(:id)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end
  
  def create
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: "Paiement de foobarlol",
      currency: 'eur',
    })
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    
  end

end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    @amount = order_params[:total_price].to_i*100 # amount in cents
    @cart = Cart.find(order_params[:cart_id])

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
      })

    @order = Order.new(
      user_id: current_user.id,
      quantity: @cart.items.count,
      price: order_params[:total_price]
    )
    if @order.save
      @order.items << @cart.items
      @cart.join_table_item_carts.destroy_all
      redirect_to root_path
    end

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to orders_path
    end

    private

    def order_params
      params.permit(:cart_id, :total_price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_current_user_profile_page?, only: [:show]

  def show
  end

  private

  def is_current_user_profile_page?
    if current_user == User.find(params[:id])
    else
      redirect_to root_path
    end
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def item_chosen
    
  end

  def bootstrap_class_for_flash(type)
    case type
      when 'notice' then "alert-info"
      when 'success' then "alert-success"
      when 'error' then "alert-danger"
      when 'alert' then "alert-warning"
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/admin/index/index.html.erb
<div class="container text-center mt-5">
  <h1>Dashboard Administrateur</h1>
  <br>
  <p>Bonjour, <%=current_user.first_name %> </p> <br>
  <p><strong>Bienvenue dans le dashboard administrateur</strong></p> <br>
  <p class="font-italic">Vous pouvez accéder à la gestion des éléments suivants :</p>
  <a class="btn btn-danger" href="<%=admin_users_path %>">Gestion des utilisateurs</a>
  <a class="btn btn-success" href="<%=admin_items_path %>">Gestion des articles</a>
  <a class="btn btn-primary" href="<%=admin_orders_path %>">Gestion des commandes</a>
</div>

app/views/layouts/_flash.html.erb
<% flash.each do |type, msg| %>
  <div class="alert <%= bootstrap_class_for_flash(type) %> alert-dismissable fade show" role="alert">
    <%= msg %>
  <button type="button" class="close" data-dismiss="alert" aria-label="Close">
    <span aria-hidden="true">×</span>
  </button>
  </div>
<% end %>

app/views/layouts/_footer.html.erb
<footer class="pt-4 my-md-5 pt-md-5 border-top container">
    <div class="row">
      <div class="col-12 col-md">
        <h3>Catz Temple</h3>
        <small class="d-block mb-3 text-muted">© 2020</small>
      </div>
      <div class="col-6 col-md">
        <h5>Catégories</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Mon profil</a></li>
          <li><a class="text-muted" href="#">Team</a></li>
          <li><a class="text-muted" href="#">Contact</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>Resources</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">API</a></li>
        </ul>
      </div>
      <div class="col-6 col-md">
        <h5>A propos</h5>
        <ul class="list-unstyled text-small">
          <li><a class="text-muted" href="#">Vie privée</a></li>
          <li><a class="text-muted" href="#">CGU</a></li>
        </ul>
      </div>
    </div>
  </footer>

app/views/layouts/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light">
  <a class="navbar-brand" href="/">Catz Temple</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarColor02" aria-controls="navbarColor02" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarColor02">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item active"></li>
    </ul>
    <form class="form-inline my-2 my-lg-0">
    <% if !user_signed_in? %>
      <%= link_to "S'inscrire", new_user_registration_path, class: "btn btn-light mr-3" %>
      <%= link_to "Connexion", new_user_session_path, class: "btn btn-primary" %>
    <% else %>
      <%= link_to cart_path(current_user.id), class: " mr-3 rounded btn btn-light" do%>
        <%= current_user.cart.items.count %> <i class="fas fa-shopping-cart text-secondary"></i>
      <% end %>
      <% if current_user.admin == true %> <%= link_to "Dashboard Admin", admin_root_path, class: "btn btn-primary mr-3" %> <% end %>
      <%= link_to "Mon profil", user_path(current_user.id), class: "btn btn-light mr-3" %>
      <%= link_to "Déconnexion", destroy_user_session_path, method: :delete, class: "btn btn-danger" %>
    <% end %>
    </form>
  </div>
</nav>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Chats</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.14.0/css/all.css" integrity="sha384-HzLeBuhoNPvSl5KYnjx0BT+WB0QEEqLprO+NBkkk5gbc67FTaL7XIGa2w1L0Xbgc" crossorigin="anonymous">
  </head>

  <body>
  <%= render 'layouts/navbar' %>
  <%= render 'layouts/flash' %>
  <!--
  <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %></p>
    </div>
  <% elsif flash[:error] %>
    <div class="alert alert-error">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:error] %>
    </div>
  <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %></p>
    </div>
  <% end %>
  -->
      <%= yield %>
  <%= render 'layouts/footer' %>

<script src="https://code.jquery.com/jquery-3.4.1.slim.min.js" integrity="sha384-J6qa4849blE2+poT4WnyKhv5vZF5SrPo0iEjwBvKU7imGFAV0wwj1yYfoRSJoZ+n" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.0/dist/umd/popper.min.js" integrity="sha384-Q6E9RHvbIyZFJoft+2mJbHaEWldlvI9IOYy5n3zV9zzTtmI3UksdQRVvoxMfooAo" crossorigin="anonymous"></script>
<script src="https://stackpath.bootstrapcdn.com/bootstrap/4.4.1/js/bootstrap.min.js" integrity="sha384-wfSDF2E50Y2D1uUdj0O3uMBJnjuUD4Ih7YwaYd1iqfktj0Uod8GCExl3Og8ifwB6" crossorigin="anonymous"></script>
  </body>
</html>