config/routes.rb
Rails.application.routes.draw do
  get 'users/show'
  devise_for :users
  resources :users, only: [:show]
  resources :carts
  resources :orders
  resources :items
  resources :join_table_item_carts, only: [:create, :destroy]
  root to: "items#index"

  namespace :admin do
    root to: "index#index"
    resources :users
    resources :items
    resources :orders, only: [:index, :destroy]
  end

end

app/models/admin.rb
module Admin
  def self.table_name_prefix
    'admin_'
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cart.rb
class Cart < ApplicationRecord
  belongs_to :user
  has_many :join_table_item_carts, dependent: :destroy
  has_many :items, through: :join_table_item_carts
end

app/models/item.rb
class Item < ApplicationRecord
  validates :title, presence: true
  validates :description, presence: true
  validates :price, presence: true
  validates :image_url, presence: true
  has_many :join_table_item_carts
  has_many :carts, through: :join_table_item_carts
  has_many :join_table_item_orders
  has_many :orders, through: :join_table_item_orders

end

app/models/join_table_item_cart.rb
class JoinTableItemCart < ApplicationRecord
  belongs_to :item
  belongs_to :cart
end

app/models/join_table_item_order.rb
class JoinTableItemOrder < ApplicationRecord
  belongs_to :item
  belongs_to :order
end

app/models/order.rb
class Order < ApplicationRecord

  after_create :new_order_mail


  # validates :item_name, presence: true
  # validates :price, presence: true
  # validates :quantity, presence: true
  # validates :payment_method, presence: true
  belongs_to :user
  has_many :join_table_item_orders, dependent: :destroy
  has_many :items, through: :join_table_item_orders

  private

  def new_order_mail
    OrderMailer.new_order_mail_to_client(self).deliver_now
    OrderMailer.new_order_mail_to_admin(self).deliver_now
  end
  
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_one :cart, dependent: :destroy
  has_many :orders, dependent: :destroy

  after_create :create_cart, :welcome_new_user

  def create_cart
    Cart.create(
      user_id: User.last.id
    )
  end

  def welcome_new_user
    UserMailer.welcome_new_user(self).deliver_now
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_devise_parameters, if: :devise_controller?

  def configure_devise_parameters
    devise_parameter_sanitizer.permit(:sign_up) {|u| u.permit(:first_name, :last_name, :email, :password, :password_confirmation)}
  end

  def is_admin?
    if user_signed_in? && current_user.admin == true
      return true
    else
      flash[:error] = "Vous n'êtes pas autorisé à effectuer cette action"
      redirect_to root_path
    end
  end
end

app/controllers/carts_controller.rb
class CartsController < ApplicationController
  before_action :authenticate_user!
  before_action :is_current_user_profile_page?, only: [:show]

  def show
    @user = current_user
    @cart = Cart.find(params[:id])
    @total_price = 0
    @cart.items.each do |item|
      @total_price += item.price 
    end
  end

  def update
    @cart_of_user = User.find(current_user.id).cart
    @cart_of_user.items << Item.find(item_params[:item_id])
    flash[:success] = flash[:success] = "Ce produit a été ajouté au panier."
    redirect_to root_path
  end

  private

  def is_current_user_profile_page?
    if current_user == User.find(params[:id])
    else
      redirect_to root_path
    end
  end
  
  def item_params
    params.permit(:item_id)
  end

  def cart_params
    params.permit(:id)
  end

end

app/controllers/charges_controller.rb
class ChargesController < ApplicationController

  def new
  end
  
  def create
    # Amount in cents
    @amount = 500
  
    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
  
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: "Paiement de foobarlol",
      currency: 'eur',
    })
  
  rescue Stripe::CardError => e
    flash[:error] = e.message
    redirect_to new_charge_path
  end
  
end

app/controllers/items_controller.rb
class ItemsController < ApplicationController
  def index
    @items = Item.all
  end

  def show
    @item = Item.find(params[:id])
    
  end

end

app/controllers/join_table_item_carts_controller.rb
class JoinTableItemCartsController < ApplicationController
  before_action :authenticate_user!
  
  def destroy
    @item = Cart.find(params[:cart_id]).items.find(params[:item_id]).join_table_item_carts.find_by(cart_id: params[:cart_id])
    @item.destroy
    flash[:success] = "Ce produit a été retiré du panier."
    redirect_to cart_path(params[:cart_id])
  end

  def create
  end
end

app/controllers/orders_controller.rb
class OrdersController < ApplicationController

  def create
    @amount = order_params[:total_price].to_i*100 # amount in cents
    @cart = Cart.find(order_params[:cart_id])

    customer = Stripe::Customer.create({
      email: params[:stripeEmail],
      source: params[:stripeToken],
    })
    charge = Stripe::Charge.create({
      customer: customer.id,
      amount: @amount,
      description: 'Rails Stripe customer',
      currency: 'eur',
      })

    @order = Order.new(
      user_id: current_user.id,
      quantity: @cart.items.count,
      price: order_params[:total_price]
    )
    if @order.save
      @order.items << @cart.items
      @cart.join_table_item_carts.destroy_all
      redirect_to root_path
    end

    rescue Stripe::CardError => e
      flash[:error] = e.message
      redirect_to orders_path
    end

    private

    def order_params
      params.permit(:cart_id, :total_price)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!
  before_action :is_current_user_profile_page?, only: [:show]

  def show
  end

  private

  def is_current_user_profile_page?
    if current_user == User.find(params[:id])
    else
      redirect_to root_path
    end
  end
  
end

app/helpers/admin/index_helper.rb
module Admin::IndexHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def item_chosen
    
  end

  def bootstrap_class_for_flash(type)
    case type
      when 'notice' then "alert-info"
      when 'success' then "alert-success"
      when 'error' then "alert-danger"
      when 'alert' then "alert-warning"
    end
  end

end

app/helpers/carts_helper.rb
module CartsHelper
end

app/helpers/charges_helper.rb
module ChargesHelper
end

app/helpers/items_helper.rb
module ItemsHelper
end

app/helpers/join_table_item_carts_helper.rb
module JoinTableItemCartsHelper
end

app/helpers/orders_helper.rb
module OrdersHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/carts/show.html.erb
<div class="jumbotron text-center">
  <h1 class="display-3">Mon panier</h1>
</div>

<div class="container p-0">
    <div class="row ml-0">
      <div class="col-8 p-0 d-inline-flex">
      
        <table class="table">
          <thead>
            <tr class="table-active row mr-0 ml-0">
              <td class="col-3"><strong>Photo</strong></td>
              <td class="col-5">Titre</td>
              <td class="col-2">Prix</td>
              <td class="col-2"></td>
            </tr>
          </thead>
          <tbody>
              <% @cart.items.each do |item| %>
                <tr class="row w-100 mr-0 ml-0">
                  <td class="col-3"><img src="<%= item.image_url %>"  alt="" class="w-50 h-auto rounded"></td>
                  <td class="col-5"><h6 class="mt-3 mb-3"><%= item.title %></h6></td>
                  <td class="col-2"><h5 class="mt-3 mb-3"><%= item.price %> €</h5></td>
                  <td class="col-2"><%= link_to "", join_table_item_cart_path(item.join_table_item_carts.find_by(cart_id: @cart.id), :cart_id => @cart.id, :item_id => item.id), method: :delete, class: "fas fa-times text-decoration-none mt-3 mb-3" %></td>
                </tr>
              <% end %>
          </tbody>
        </table>
      </div>
      <div class="col-4 bg-light p-4 align-content-between flex-end">
        <h4><strong>Total de la commande :</h4>
        <h3><strong><%= @total_price %> €</h3>
      </div>
    </div>

    <div class="row pt-3 pb-3 pl-0 pr-0 align-middle">
      <div class="col-8 p-0 m-0"></div>
      <div class="col-4 p-0 m-0 text-center">
        <%= form_tag orders_path(:cart_id => @cart.id, :total_price => @total_price) do %>
          <article>
            <% if flash[:error].present? %>
              <div id="error_explanation">
                <p><%= flash[:error] %></p>
              </div>
            <% end %>
          </article>

          <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          style="display: none;"
                  data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
                  data-description="Paiement de la commande"
                  data-amount="<%= @total_price*100 %>"
                  data-currency='eur'
                  data-label = "Commander"
                  data-image="https://thumbs.dreamstime.com/t/cash-currency-euro-money-price-shopping-outline-icon-signs-symbols-can-be-used-web-logo-mobile-app-ui-ux-white-146328719.jpg"
                  data-locale="auto">
          </script>

        <% end %>
      </div>
    </div>
</div>